version: '2'
services:
  play:
    command: /bin/sh -c "npm i && npm run start"
    image: node
    working_dir: /opt
    volumes:
     - .:/opt
    environment:
      TERM: dumb
  test:
    command: /bin/sh -c "npm i && npm run test"
    image: node
    working_dir: /opt
    volumes:
     - .:/opt
    environment:
      TERM: dumb
