import {BooleanOperator, BTreeLeaf} from './b-exp-tree';
import {BTree} from './b-tree/index';

// This is a dummy functionl, the real parser is generated by pegjs
export function parse(str: string): BTree<BooleanOperator, BTreeLeaf> | BTreeLeaf {
  return;
}
